image: "docker:27-dind"
variables:
  DOCKER_TLS_CERTDIR: "/certs/"
services:
  - docker:dind
molecule:
  stage: test
  tags:
  - saxonee
  script:
  - apk add --no-cache
    python3 python3-dev py3-pip  gcc git curl build-base
    autoconf automake py3-cryptography linux-headers
    musl-dev libffi-dev openssl-dev openssl ca-certificates
  - update-ca-certificates --fresh
  - docker info
  - python3 --version
  - python3 -m venv molecule-venv 
  - . molecule-venv/bin/activate
  - pip install ansible molecule-plugins[docker]
  - ansible --version
  - molecule --version
  - molecule test
