- name: "Delete Fuseki compacting"
  file:
    path: /etc/systemd/system/fuseki-compact.service
    state: absent

- name: "Disable fuseki compacting timer"
  systemd:
    daemon_reload: "yes"
    name: "fuseki-compact.timer"
    state: disabled

- name: "Remove fuseki compacting Timer"
  file:
    src: "fuseki-compact.timer.j2"
    path: "/etc/systemd/system/fuseki-compact.timer"
    state: absent

- import_tasks: "sysctl_sudoers.yml"
