- name: "template shiro.ini"
  template:
    src: "shiro.ini.j2"
    dest: "{{ fuseki_base }}/shiro.ini"
    backup: true
  become: true
  notify: "fuseki restart"

  #- name: "debug shiro.ini"
  #shell: "cat /var/fuseki/shiro.ini"
  #register: "shiro_cat_output"

  #- name: "debug shiro.ini"
  #debug:
  #  msg: "{{ shiro_cat_output }}"
