---
- name: Converge
  hosts: all
  become_method: su

  tasks:
    - name: "update dnf"
      dnf:
        name: "*"
        state: "latest"
      become: true

    - name: "install java version"
      package:
        name:  ["which", "java-11-openjdk", "java-11-openjdk-headless"]
      become: true

    - name: "Include fuseki"
      include_role:
        name: "fuseki"
      vars:
        fuseki_workspace: "/tmp/"
        fuseki_configurations:
        - name: "test-db"
          read_write: True
          union_default_graph: False


