---
- name: Converge
  hosts: all
  become_method: su
  tasks:
    - name: "update dnf"
      dnf:
        name: "*"
        state: "latest"
      become: true

    - name: "install required dependencies"
      package:
        name:  ["unzip","which", "java-21-openjdk", "java-21-openjdk-headless"]
      become: true

    - name: "Include fuseki"
      include_role:
        name: "fuseki"
      vars:
        fuseki_version: "5.2.0"
        fuseki_checksum: "650d4576927cb4e330c372c46f76dde3fbd683b59cc692bac501b545097402c58c2254b25502e4225ba6f7d4c79ee12c5e43b78124115dbbe6371c487aa8604f"
        jena_checksum: "9a66044573ca269c0a9a1191fe7a8e1925f2d77e2e0bdadddd68616a1bafed1d9819c0b2988dd03614ec778a3882ccb091d825976fc0837406916f9f001b701c"
        fuseki_staging: true
        fuseki_shiro_url_rules: |

            /$/status  = authcBasic,user[admin]
        fuseki_shiro_users:   
        - name: "admin"
          password_stanza: "$shiro2$argon2id$v=19$t=1,m=65536,p=4$Wr/2XKxWeYZt8JE5HCONQw$yev4bLiGzbeIZ8qDWrIY7J2msL2vRO/aYksb4RMeX7Y"
        fuseki_workspace: "/tmp/"
        service_enhancer_url: "https://github.com/OyvindLGjesdal/jena/releases/download/service-enhancer-shaded/jena-serviceenhancer-5.2.0-SNAPSHOT.jar"
        #
        fuseki_modules:
                #
        # sis-embedded-data packaged with shading enabled
        - "https://github.com/OyvindLGjesdal/jena/releases/download/service-enhancer-shaded/jena-sis-nonfree-1.0.jar"

                #
                # - "https://repo1.maven.org/maven2/org/apache/sis/non-free/sis-embedded-data/1.4/sis-embedded-data-1.4.jar"
        fuseki_configurations:
        - name: "test-db_all"
          read_write: true
          write_timeout: "70000,200000"
          union_default_graph: true
          lucene: true
          geosparql: true

          service_enhancer: true
          luceneStoreValues: true
          prefix: |
            @prefix ex: <http://example.org/Schema#> .
          entity_map: |
            text:defaultField     "label" ;
            text:entityField      "uri" ;
            text:uidField         "uid" ;
            text:langField        "lang" ;
            text:graphField       "graph" ;
            text:map (
              [ text:field "label" ;

               text:predicate ex:name ] )
     
